models.py
#-*- coding: utf-8 -*-

from .utils import *

################################################################################

class TeamRole(models.Model):
    name       = models.CharField(max_length=128)

    def __str__(self):     return str(self.name)
    def __unicode__(self): return unicode(self.name)

#*******************************************************************************

class TeamMember(models.Model):
    identity   = models.OneToOneField(Identity, related_name='membership')

    is_founder = models.BooleanField(default=False)
    roles      = models.ManyToManyField(TeamRole, blank=True, related_name='profiles')

    joined_on  = models.DateTimeField(auto_now_add=True)

    def __str__(self):     return str(self.identity)
    def __unicode__(self): return unicode(self.identity)

################################################################################

@Reactor.orm.register_model('team')
class Team(models.Model):
    organization = models.ForeignKey(Organization)

    name         = models.CharField(max_length=64)
    title        = models.CharField(max_length=256, blank=True)

    created_on   = models.DateTimeField(auto_now_add=True)

    def __str__(self):     return str(self.title or self.name)
    def __unicode__(self): return unicode(self.title or self.name)

#*******************************************************************************

@Reactor.orm.register_model('project')
class Project(models.Model):
    organization = models.ForeignKey(Organization)

    name         = models.CharField(max_length=64)
    title        = models.CharField(max_length=256, blank=True)

    teams        = models.ManyToManyField(Team, blank=True)

    progress     = property(lambda self: 57)

    created_on   = models.DateTimeField(auto_now_add=True)

    def __str__(self):     return str(self.title or self.name)
    def __unicode__(self): return unicode(self.title or self.name)

################################################################################

from django.db import models
from django.contrib import admin

import datetime
#from settings import printdebug

EXTRA_SAVING_ACTIONS = True

class HistoryEntry(models.Model):
	"""(HistoryEntry description)"""
	uri = models.CharField(max_length=350, )	
	description = models.TextField(blank=True, verbose_name="description")
	pubdate = models.DateTimeField(null=True, blank=True, verbose_name="date added" )
	score = models.IntegerField(blank=True, null=True)

	class Admin(admin.ModelAdmin):
		list_display = ('id', 'uri', 'pubdate', 'score')
		search_fields = ('uri',)
		list_filter = ('pubdate', )
		
	def save(self, force_insert=False, force_update=False):
		if EXTRA_SAVING_ACTIONS:
			super(HistoryEntry, self).save(force_insert, force_update)
			self.pubdate = datetime.datetime.today()
			if self.score:
				self.score = self.score + 1
			else:
				self.score = 1
		super(HistoryEntry, self).save(force_insert, force_update)	
			
	class Meta:
		verbose_name_plural="HistoryEntry"
		verbose_name = "HistoryEntry"
		ordering = ["id"]

	def __unicode__(self):
		return "HistoryEntry %d" % self.id


# TODO: put in admin.py
admin.site.register(HistoryEntry, HistoryEntry.Admin)

################################################################################

import logging
from time import time
import six

from django.db import models, DatabaseError
from django.core.urlresolvers import reverse
from django.conf import settings

from . import app_settings
from uchikoma.console.utils import (passes_blacklist, swap_params, extract_params, shared_dict_update, get_connection,
                            get_s3_connection, get_params_for_url)

MSG_FAILED_BLACKLIST = "Query failed the SQL blacklist: %s"


logger = logging.getLogger(__name__)


class Query(models.Model):
    title = models.CharField(max_length=255)
    sql = models.TextField()
    description = models.TextField(null=True, blank=True)
    created_by_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_run_date = models.DateTimeField(auto_now=True)
    snapshot = models.BooleanField(default=False, help_text="Include in snapshot task (if enabled)")

    def __init__(self, *args, **kwargs):
        self.params = kwargs.get('params')
        kwargs.pop('params', None)
        super(Query, self).__init__(*args, **kwargs)

    class Meta:
        ordering = ['title']
        verbose_name_plural = 'Queries'

    def __unicode__(self):
        return six.text_type(self.title)

    def get_run_count(self):
        return self.querylog_set.count()

    def avg_duration(self):
        return self.querylog_set.aggregate(models.Avg('duration'))['duration__avg']

    def passes_blacklist(self):
        return passes_blacklist(self.final_sql())

    def final_sql(self):
        return swap_params(self.sql, self.available_params())

    def execute_query_only(self):
        return QueryResult(self.final_sql())

    def execute_with_logging(self, executing_user):
        ql = self.log(executing_user)
        ret = self.execute()
        ql.duration = ret.duration
        ql.save()
        return ret, ql

    def execute(self):
        ret = self.execute_query_only()
        ret.process()
        return ret

    def available_params(self):
        """
            Merge parameter values into a dictionary of available parameters

        :param param_values: A dictionary of Query param values.
        :return: A merged dictionary of parameter names and values. Values of non-existent parameters are removed.
        """

        p = extract_params(self.sql)
        if self.params:
            shared_dict_update(p, self.params)
        return p

    def get_absolute_url(self):
        return reverse("query_detail", kwargs={'query_id': self.id})

    @property
    def params_for_url(self):
        return get_params_for_url(self)

    def log(self, user=None):
        if user and user.is_anonymous():
            user = None
        ql = QueryLog(sql=self.final_sql(), query_id=self.id, run_by_user=user)
        ql.save()
        return ql

    @property
    def shared(self):
        return self.id in set(sum(app_settings.EXPLORER_GET_USER_QUERY_VIEWS().values(), []))

    @property
    def snapshots(self):
        if app_settings.ENABLE_TASKS:
            conn = get_s3_connection()
            res = conn.list('query-%s.snap-' % self.id)
            return sorted(res, key=lambda s: s['last_modified'])


class QueryLog(models.Model):

    sql = models.TextField(null=True, blank=True)
    query = models.ForeignKey(Query, null=True, blank=True, on_delete=models.SET_NULL)
    run_by_user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    run_at = models.DateTimeField(auto_now_add=True)
    duration = models.FloatField(blank=True, null=True)  # milliseconds

    @property
    def is_playground(self):
        return self.query_id is None

    class Meta:
        ordering = ['-run_at']


class QueryResult(object):

    def __init__(self, sql):

        self.sql = sql

        cursor, duration = self.execute_query()

        self._description = cursor.description or []
        self._data = [list(r) for r in cursor.fetchall()]
        self.duration = duration

        cursor.close()

        self._headers = self._get_headers()
        self._summary = {}

    @property
    def data(self):
        return self._data or []

    @property
    def headers(self):
        return self._headers or []

    @property
    def header_strings(self):
        return [str(h) for h in self.headers]

    def _get_headers(self):
        return [ColumnHeader(d[0]) for d in self._description] if self._description else [ColumnHeader('--')]

    def _get_numerics(self):
        conn = get_connection()
        if hasattr(conn.Database, "NUMBER"):
            return [ix for ix, c in enumerate(self._description) if hasattr(c, 'type_code') and c.type_code in conn.Database.NUMBER.values]
        elif self.data:
            d = self.data[0]
            return [ix for ix, _ in enumerate(self._description) if not isinstance(d[ix], six.string_types) and six.text_type(d[ix]).isnumeric()]
        return []

    def _get_transforms(self):
        transforms = dict(app_settings.EXPLORER_TRANSFORMS)
        return [(ix, transforms[str(h)]) for ix, h in enumerate(self.headers) if str(h) in transforms.keys()]

    def column(self, ix):
        return [r[ix] for r in self.data]

    def process(self):
        start_time = time()

        self.process_columns()
        self.process_rows()

        logger.info("Explorer Query Processing took %sms." % ((time() - start_time) * 1000))

    def process_columns(self):
        for ix in self._get_numerics():
            self.headers[ix].add_summary(self.column(ix))

    def process_rows(self):
        transforms = self._get_transforms()
        if transforms:
            for r in self.data:
                for ix, t in transforms:
                    r[ix] = t.format(str(r[ix]))

    def execute_query(self):
        conn = get_connection()
        cursor = conn.cursor()
        start_time = time()

        try:
            cursor.execute(self.sql)
        except DatabaseError as e:
            cursor.close()
            raise e

        return cursor, ((time() - start_time) * 1000)


class ColumnHeader(object):

    def __init__(self, title):
        self.title = title.strip()
        self.summary = None

    def add_summary(self, column):
        self.summary = ColumnSummary(self, column)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title


class ColumnStat(object):

    def __init__(self, label, statfn, precision=2, handles_null=False):
        self.label = label
        self.statfn = statfn
        self.precision = precision
        self.handles_null = handles_null

    def __call__(self, coldata):

templates/explorer/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SQL Explorer{% if query %} - {{ query.title }}{% elif title %} - {{ title }}{% endif %}</title>

    <link href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.15.2/codemirror.min.css" rel="stylesheet" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/pivottable/2.0.0/pivot.min.css" rel="stylesheet" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'explorer/explorer.css' %}" />

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>

    <script src="{% static 'explorer/jquery-ui.11.4.min.js' %}"></script>
    <script src="{% static 'explorer/explorer.js' %}"></script>
    <script type="text/javascript">
        dataUrl = "{{ dataUrl }}";
        queryId = "{% firstof query.id 'new' %}";
    </script>
</head>

<body>
    <div id="wrap" class="wrap">
        {% block sql_explorer_navbar %}
            <div class="navbar navbar-default navbar-static-top" role="navigation">
              <div class="container">
                <div class="navbar-header">
                  <a class="navbar-brand" href="{% url "explorer_index" %}">SQL Explorer</a>
                </div>
                <div class="navbar-collapse collapse">
                  <ul class="nav navbar-nav">
                    {% block sql_explorer_navlinks %}{% endblock %}
                  </ul>
                </div>
              </div>
            </div>
        {% endblock %}
        {% block sql_explorer_content_wrapper %}
          <div class="container">
            <div class="starter-template">
            {% block sql_explorer_content %}{% endblock %}
            </div>
          </div>
        {% endblock sql_explorer_content_wrapper %}
    </div>
    {% block sql_explorer_footer %}
        <div class="container">
            <div class="row">
              <div class="col-md-12 text-center">
                    <p class="text-muted">
                        Powered by <a href="https://www.github.com/groveco/django-sql-explorer/">django-sql-explorer</a> from
                        <a href="https://www.grove.co">Grove Collaborative</a>.
                    </p>
              </div>
            </div>
        </div>
    {% endblock %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.7.0/underscore-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/list.js/1.2.0/list.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.15.2/codemirror.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.15.2/mode/sql/sql.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.15.2/addon/comment/comment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/floatthead/1.4.0/jquery.floatThead-slim.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/pivottable/2.0.2/pivot.min.js"></script>
    {% block sql_explorer_scripts %}{% endblock %}
</body>

</html>

templates/explorer/export_buttons.html
<div class="form-group">
    <div class="text-center">
        <div class="btn-group">
            {% for key, name in exporters.items %}
                {% if query %}
                    {% if query.params %}
                      <a href="{% url "download_query" query.id %}?format={{ key }}&params={{ query.params_for_url }}" class="btn btn-default">{{ name }}</a>
                    {% else %}
                      <a href="{% url "download_query" query.id %}?format={{ key }}" class="btn btn-default">{{ name }}</a>
                    {% endif %}
                {% else %}
                    <input type="submit" value="{{ name }}" data-format="{{ key }}" class="btn btn-default download-button" />
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

templates/explorer/params.html
{% if params %}
<div class="panel-footer">
  <div class="form-inline">
  {% for k, v in params.items %}
      <div class="form-group">
          <label for="{{ k }}_param" class="control-label col-sm-4">{{ k }}:</label>
          <div class="col-sm-7">
              <input type="text" data-param="{{ k }}" class="param form-control" name="{{ k }}_param" placeholder="parameter" value="{{ v }}" />
          </div>
          <div class="col-sm-1"></div>
      </div>
  {% endfor %}
  </div>
</div>
{% endif %}

templates/explorer/play.html
{% extends "explorer/base.html" %}

{% load explorer_tags %}

{% block sql_explorer_navlinks %}
    {% if can_change %}
      <li><a href="{% url "query_create" %}">New Query</a></li>
      <li class="active"><a href="">Playground</a></li>
      <li><a href="{% url "explorer_logs" %}">Logs</a></li>
    {% endif %}
{% endblock %}

{% block sql_explorer_content %}
<div class="row">
    <div id="query_area" class="col-md-12">
        <h2>Playground</h2>
        <p>The playground is for experimenting and writing ad-hoc queries. By default, nothing you do here will be saved.</p>
        <form role="form" action="{% url "explorer_playground" %}" method="post" id="editor" class="playground-form">{% csrf_token %}
            {% if error %}
                <div class="alert alert-danger">{{ error|escape }}</div>
            {% endif %}
            <div class="panel panel-default sql-panel">
                <div class="panel-heading">
                  <div class="row">
                    <div class="col-md-6">
                      <span class="panel-title">Playground SQL</span>
                    </div>
                    {% if ql_id %}
                        <div class="col-md-6 text-right">
                          <small><a href="{% url "explorer_playground" %}?querylog_id={{ ql_id }}"><i class="glyphicon glyphicon-link"></i></a></small>
                        </div>
                    {% endif %}
                  </div>
                </div>
                <div class="panel-content">
                    <textarea class="form-control" cols="40" id="id_sql" name="sql" rows="20">{{ query.sql }}</textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="text-center">
                    <div class="btn-group">
                        <input type="submit" value="Refresh Preview" id="refresh_play_button" class="btn btn-default"/>
                        <input type="submit" value="Save As New Query" id="create_button" class="btn btn-default"/>
                        <button type="button" class="btn btn-default" id="show_schema_button">Show Schema</button>
                        <button type="button" class="btn btn-default" id="hide_schema_button" style="display: none;">Hide Schema</button>
                        <button type="button" class="btn btn-default" id="format_button">Format</button>
                    </div>
                </div>
            </div>
            {% export_buttons %}
            <input type="hidden" value="Playground Query" name="title" />
        </form>
    </div>
    <div id="schema" style="display: none;">
        <iframe src="" height="630px" frameBorder="0" id="schema_frame"></iframe>
    </div>
</div>
{% include 'explorer/preview_pane.html' %}

{% endblock %}

{% block sql_explorer_scripts %}
    <script>
        $(function() {
            var e = new ExplorerEditor(queryId, dataUrl);
        });
    </script>
{% endblock %}

templates/explorer/preview_pane.html
{% if headers %}
    <div class="row">
        <div class="col-md-12">
            <div role="tabpanel">
                <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class="active"><a href="#previewpane" aria-controls="previewpane" role="tab" data-toggle="tab" id="preview-tab-label">Preview</a></li>
                    {% if query.id and query.snapshot %}<li role="presentation"><a href="#snapshots" aria-controls="snapshots" role="tab" data-toggle="tab">Snapshots</a></li>{% endif %}
                    {% if data %}<li role="presentation"><a href="#pivot" aria-controls="pivot" role="tab" data-toggle="tab" id="pivot-tab-label">Pivot</a></li>{% endif %}
                </ul>
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active" id="previewpane">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                              <div class="row">
                                <div class="col-md-6">
                                  <span class="panel-title">Execution time: {{ duration|floatformat:2 }} ms</span>
                                </div>
                                <div class="col-md-6 text-right">
                                  <span class="row-control">
                                      {% if rows > total_rows %}
                                          Showing {{ total_rows }} of {{ total_rows }} total rows.
                                      {% else %}
                                          First <input class="rows-input" type="text" name="rows" id="rows" value="{{ rows }}" /> of {{ total_rows }} total rows.
                                      {% endif %}
                                  </span>
                                </div>
                              </div>
                            </div>
                            <div class="overflow-wrapper">
                                <table class="table table-striped table-hover" id="preview">
                                    <thead class="data-headers">
                                        <tr>
                                            {% for h in headers %}
                                                <th class="preview-header"><span class="sort" data-sort="{{ forloop.counter0 }}" data-dir="asc">{{ h }}</span></th>
                                            {% endfor %}
                                        </tr>
                                        <tr class="stats-th">
                                        {% for h in headers %}
                                          <th>
                                            {% if h.summary %}
                                              <i class="stats-expand glyphicon glyphicon-education"></i>
                                              <div class="stats-wrapper">
                                                  {% for label, value in h.summary.stats.items %}
                                                      <div class="stat-wrapper"><span class="stat-label">{{ label }}:&nbsp;</span><span class="stat-value">{{ value }}</span></div>
                                                  {% endfor %}
                                              </div>
                                            {% endif %}
                                          </th>
                                        {% endfor %}
                                        </tr>

                                    </thead>
                                    <tbody class="list">
                                        {% if data %}
                                            {% for row in data %}
                                            <tr class="data-row">
                                                {% for i in row %}
                                                    <td class="{{ forloop.counter0 }}">{% autoescape off %}{{ i }}{% endautoescape %}</td>
                                                {% endfor %}
                                            </tr>
                                            {% endfor %}
                                        {% else %}
                                            <tr class="text-center"><td colspan="{{ headers|length }}">Empty Resultset</td></tr>
                                        {% endif %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    {% if query.id and query.snapshot and query.snapshots %}
                        <div role="tabpanel" class="tab-pane" id="snapshots">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <span class="panel-title">{{ snapshots|length }} Snapshots <small>(oldest first)</small></span>
                                </div>
                                <div class="overflow-wrapper">
                                <p>
                                    <ul>
                                    {%  for s in snapshots %}
                                        <li><a href='http://s3.amazonaws.com/{{ bucket }}/{{ s.key }}'>{{ s.last_modified }}</a></li>
                                    {% endfor %}
                                    </ul>
                                </p>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                  {% if data %}
                    <div role="tabpanel" class="tab-pane" id="pivot">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="row">
                                  <div class="col-md-6">
                                    <span class="panel-title">Pivot</span>
                                  </div>
                                  <div class="col-md-6 text-right">
                                    <small><a id="pivot-bookmark" data-baseurl="{% url "explorer_playground" %}?querylog_id={{ ql_id }}" href="#"><i class="glyphicon glyphicon-link"></i></a></small>
                                  </div>
                                </div>
                            </div>
                            <div class="overflow-wrapper">
                              <div class="pivot-table">
                            </div>
                        </div>
                    </div>
                  {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endif %}

templates/explorer/query.html
{% extends "explorer/base.html" %}

{% load explorer_tags %}

{% block sql_explorer_navlinks %}
    {% if can_change %}
      <li{% if not query %} class="active" {% endif %}><a href="{% url "query_create" %}">New Query</a></li>
      <li><a href="{% url "explorer_playground" %}">Playground</a></li>
    {% endif %}
    {% if query %}<li class="active"><a href="">Query Detail</a></li>{% endif %}
    <li><a href="{% url "explorer_logs" %}">Logs</a></li>
{% endblock %}

{% block sql_explorer_content %}
<div class="row">
    <div id="query_area" class="query-area col-md-12">
        <h2>{% if query %}{{ query.title }}{% if shared %}<small>&nbsp;&nbsp;shared</small>{% endif %}{% else %}New Query{% endif %}</h2>
        {% if query %}
            <div class="text-right">
                <a href="{% url "explorer_logs" %}?query_id={{ query.id }}"><h2 class="small">History</h2></a>
            </div>
        {% endif %}
        {% if message %}
            <div class="alert alert-info">{{ message }}</div>
        {% endif %}
        <div>
            {% if query %}
                <form role="form" class="form-horizontal" action="{% url "query_detail" query.id %}" method="post" id="editor">{% csrf_token %}
            {% else %}
                <form role="form" class="form-horizontal" action="{% url "query_create" %}" method="post" id="editor">{% csrf_token %}
            {% endif %}
                {% if error %}
                    <div class="alert alert-danger">{{ error|escape }}</div>
                {% endif %}
                {{ form.non_field_errors }}
                <div class="form-group">
                    {% if form.title.errors %}{% for error in form.title.errors %}
                        <div class="alert alert-danger">{{ error|escape }}</div>
                    {% endfor %}{% endif %}
                    <label for="id_title" class="col-sm-2 control-label">Title</label>
                    <div class="col-sm-10">
                        <input class="form-control" id="id_title" maxlength="255" name="title" type="text" {% if not can_change %}disabled{% endif %} value="{{ form.title.value|default_if_none:"" }}" />
                    </div>
                </div>
                <div class="form-group">
                    {% if form.description.errors %}
                        <div class="alert alert-danger">{{ form.description.errors }}</div>
                    {% endif %}
                    <label for="id_title" class="col-sm-2 control-label">Description</label>
                    <div class="col-sm-10">
                        <textarea class="form-control" cols="40" id="id_description" name="description" {% if not can_change %}disabled{% endif %} rows="2">{{ form.description.value|default_if_none:"" }}</textarea>
                    </div>
                </div>
                {% if query %}
                    <div class="form-group">
                        {% if form.created_by_user.errors %}
                            <div class="alert alert-danger">{{ form.created_by_user.errors }}</div>
                        {% endif %}
                        <label for="id_title" class="col-sm-2 control-label">Created By</label>
                        <div class="col-sm-10">
                            <span class="form-control" disabled id="id_created_by_user_label" maxlength="255" name="created_by_user_label">{{ form.created_by_user_email }}</span>
                            <input type="hidden" id="id_created_by_user" name="created_by_user" value="{{ form.created_by_user_id }}" />
                        </div>
                    </div>
                {% endif %}
                {% if form.sql.errors %}{% for error in form.sql.errors %}
                    <div class="alert alert-danger">{{ error|escape }}</div>
                {% endfor %}{% endif %}
                <div class="panel panel-default sql-panel">
                    <div class="panel-heading">
                        <span class="panel-title">SQL</span>
                    </div>
                    <div class="panel-content">
                        <textarea class="form-control" {% if not can_change %} disabled {% endif %} cols="40" id="id_sql" name="sql" rows="20">{{ form.sql.value|default_if_none:"" }}</textarea>
                    </div>
                    {% if params %}
                      {% include 'explorer/params.html' %}
                    {% endif %}
                </div>
                <div class="form-group">
                    <div class="text-center">
                        <div class="btn-group">
                            {% if can_change %}
                                <input type="submit" value="Save & Run" class="btn btn-default" id="save_button" />
                                {% if query %}
                                     <input type="submit" value="Open in Playground" class="btn btn-default" id="playground_button"/>
                                {%  endif %}
                                <button type="button" class="btn btn-default" id="show_schema_button">Show Schema</button>
                                <button type="button" class="btn btn-default" id="hide_schema_button" style="display: none;">Hide Schema</button>
                                <button type="button" class="btn btn-default" id="format_button">Format</button>
                            {% else %}
                                <input type="submit" value="Refresh" class="btn btn-default" id="refresh_button" />
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% export_buttons query %}
            </form>
        </div>
    </div>
    <div id="schema" style="display: none;">
        <iframe src="" height="630px" frameBorder="0" id="schema_frame"></iframe>
    </div>
</div>
{% include 'explorer/preview_pane.html' %}
<div class="row">
  <div class="col-md-6">
    {% if query and can_change and tasks_enabled %}
      {{ form.snapshot }} Snapshot
    {% endif %}
  </div>
  <div class="col-md-6 text-right">
    {% if query.avg_duration %}
      Avg. execution: {{ query.avg_duration|floatformat:2 }}ms
    {% endif %}
  </div>
</div>
{% endblock %}

{% block sql_explorer_scripts %}
    <script>
        $(function() {
            var e = new ExplorerEditor(queryId, dataUrl);
        });
    </script>
{% endblock %}

templates/explorer/query_confirm_delete.html
{% extends "explorer/base.html" %}

{% block sql_explorer_content %}
    <form method="post">{% csrf_token %}
        <div class="alert alert-info">
            Are you sure you want to delete "{{ object.title }}" ?
        </div>
        <div>
            <input type="submit" value="Delete Query" class="btn btn-default" />
        </div>
    </form>
{%  endblock %}